JSON constant name clashing fix
this prevents the following exception:
undefined method `pretty_generate' for ReqresRspec::Formatters::JSON:Class
 (NoMethodError)